fieldLayouts:
  98098832-58a3-4687-ad9b-17eed58d4433:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 72db41f4-c7b2-42d4-a42a-4aeb2703754b
            warning: null
            width: 100
          -
            fieldUid: 35a0942c-9243-46e3-bc87-7e13ed35879c # Product Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d50cfa37-4bab-480b-bbb2-8fc6d0fe5af9
            warning: null
            width: 100
          -
            fieldUid: ff61171f-2c08-433e-8b8d-c1cbdb7df74f # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8a9dd4f-3714-49ff-a7fe-13ddc746dd11
            warning: null
            width: 100
          -
            fieldUid: 59b05f1c-b9fd-45c0-b2f7-92e14d24210c # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5522f20-e076-4d19-bc7b-b7eb270c3307
            warning: null
            width: 100
          -
            fieldUid: c4175752-8b89-40cf-807e-81917ed326b7 # Product Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b622d1c-20db-4446-b0d1-8e0b2e9a45c2
            warning: null
            width: 100
        name: Content
        uid: a5b19c81-8819-4c1e-b96a-45195f33d4fe
handle: default
hasTitleField: true
name: 'Product Options'
section: 405a4b54-d61e-43fb-9302-eff77c6f3870 # Products
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
