defaultPlacement: end
fieldLayouts:
  45a93cfe-074e-4cfd-a43f-1e1baae27f79:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 1ec8119f-f969-4b58-9411-1f074c811ef6
            warning: null
            width: 100
          -
            fieldUid: afbd4ef2-b8ec-45a8-ac7a-8fa251beda20 # Category Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6765cd29-d62f-444f-8e5d-5365a16b8d0d
            warning: null
            width: 100
        name: Content
        uid: 1a2f97fa-fe2e-4aa3-957c-a473a226528d
handle: category
name: 'Products Category'
siteSettings:
  8c24854d-2b25-4b0f-8843-0d41ff0610bb: # ICE
    hasUrls: true
    template: category/_entry.twig
    uriFormat: 'category/{slug}'
structure:
  maxLevels: null
  uid: be14d1a3-8789-422c-b5ff-62bf4fb4fefd
